# Generated by Django 4.1.5 on 2023-01-21 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='title_tag',
            field=models.CharField(default='title', max_length=255),
        ),
    ]
