# Generated by Django 4.1.5 on 2023-01-23 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_podcaster'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Podcaster',
            new_name='Podcast',
        ),
    ]
