# Generated by Django 4.1.5 on 2023-01-23 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_rename_podcaster_podcast'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcast',
            name='title',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='podcast',
            name='url',
            field=models.CharField(max_length=500),
        ),
    ]
