# Generated by Django 4.1.5 on 2023-01-23 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_podcast_title_alter_podcast_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcast',
            name='url',
            field=models.URLField(),
        ),
    ]
