# Generated by Django 4.1.5 on 2023-01-23 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_podcast_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='header_image',
            new_name='image',
        ),
        migrations.AlterField(
            model_name='podcast',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='url',
            field=models.CharField(max_length=500),
        ),
    ]
