# Generated by Django 4.1.5 on 2023-01-23 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_rename_header_image_article_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(default='', upload_to='images/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='snippet',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
